name: predict

# for compability
lr: 1

# ddim sampling
ddim_steps: 128
eta: 0.0
cfg_scale: 1.5

defaults:
  - _self_
  - data: flowers
  - location: pc
  - diffusion: ldm_based
  - style_sampling: nearby
  - style_agg: linear
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .